config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#welcome_page'
  get 'static_pages/home'

  get 'comments/new'
  post 'comments/show'
  post 'notes/show_user_notes'
  resources :notes
  resources :notebooks
  resources :comments
  resources :relationships,       only: [:create, :destroy]
  
  post 'search' => 'notes#search'
  get 'search' => 'notes#search'
  post 'upload-note' => 'notes#upload_note'
  post 'edit_notes' => 'notes#edit_notes'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions" }
  resources  :users, :only => [:index, :show] do
    member do
      get :following, :followers
    end
  end

  get 'feed' => 'users#feed'

  
end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :title, presence: true
	validates :content, presence: true
	belongs_to :user
	belongs_to :notebook
	has_many :comments
	default_scope -> { order(created_at: :desc) }
	acts_as_votable
	#searchable do
    #	text :title, :boost => 2
    #	text :content
	#end
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :avatar, content_type: { content_type: ["application/pdf", /\Aimage/] }

  # 	validate  :picture_size

  # private

  #   # Validates the size of an uploaded picture.
  #   def picture_size
  #     if avatar.size > 5.megabytes
  #       errors.add(:avatar, "should be less than 5MB")
  #     end
  #   end



end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :search]
  respond_to :json, :html

  def search
    # if user_signed_in?
    #   @notebooks = current_user.notebooks if stale?(current_user.notebooks.all)
    # end
    if request.post?
      @keyword = params[:search]
      Rails.application.config.old = @keyword
      @notes = Note.where("(title LIKE '#{@keyword}%') OR (content LIKE '#{@keyword}%') OR (university LIKE '#{@keyword}%') OR (professor LIKE '#{@keyword}%') OR (class_subject LIKE '#{@keyword}%')").paginate(:page => params[:page], :per_page => 15)
      return
    end
    @notes = Note.where("(title LIKE '#{Rails.application.config.old}%') OR (content LIKE '#{Rails.application.config.old}%') OR (university LIKE '#{Rails.application.config.old}%') OR (professor LIKE '#{Rails.application.config.old}%') OR (class_subject LIKE '#{Rails.application.config.old}%')").paginate(:page => params[:page], :per_page => 15)
  end

  def show_user_notes
    @user = User.find(params[:user_id])
    @notes = @user.notes.paginate(page: params[:page])
  end

  def index
    @notes = current_user.notes.paginate(page: params[:page], :per_page => 15)
  end


  def new
    @notebooks = current_user.notebooks if stale?(current_user.notebooks.all)
  end

  def destroy
    @note = Note.find(params[:id])
    if Note.find(params[:id]).destroy
      flash[:success] = "Note deleted"
      redirect_to root_url
    else
      flash[:success] = "Sorry, couldn't delete"
      redirect_to @note
    end

 end

  def create
  	 @note = current_user.notes.build(note_params)
    
    if @note.save
      #flash.now[:success] = "Nice one!"
      #flash.keep(:success)
      #redirect_to root_url
      #render :js => "window.location = '#{note_path(@note)}"
      respond_to do |format|
        format.html {render nothing: true, status: 200} 
        format.json {render nothing: true, status: 200} 
      end
    
    else
      #flash.now[:alert] = "Oops! Say something before submitting."
      #flash.keep(:alert)
      respond_to do |format|
        format.html {render nothing: false, status: 400} 
        format.json {render nothing: false, status: 400}
      end
    end
  end

  # edit notes
  def edit
    @notebooks = current_user.notebooks if stale?(current_user.notebooks.all)
    @note = Note.find(params[:id])
  end

  def edit_notes
    #updated notes if the note id is already existed
      @note = Note.find(params[:id])
      
      @note.update(title: params[:note][:title])
      @note.update(content: params[:note][:content])
      @note.update(university: params[:note][:university])
      @note.update(notebook_id: params[:note][:notebook_id])
      @note.update(class_subject: params[:note][:class_subject])
      @note.update(professor: params[:note][:professor])

      if @note.save
      respond_to do |format|
        format.html {render nothing: true, status: 200} 
        format.json {render nothing: true, status: 200} 
      end
    
    else
      respond_to do |format|
        format.html {render nothing: false, status: 400} 
        format.json {render nothing: false, status: 400}
      end
    end
  end



  def update
    @note = Note.find(params[:id])

    if(params[:upvote])
      @note.upvote_by current_user
      @vote_type = :upvote
      flash.now[:success] = "Upvoted!"
      respond_to do |format|
        format.html { redirect_to @note }
        format.js
      end

    elsif(params[:downvote])
      @note.downvote_by current_user
      flash.now[:alert] = "Downvoted!"
      @vote_type = :downvote
      respond_to do |format|
        format.html { redirect_to @note }
        format.js
      end
    end 


  end


  def show
    #@notebooks = current_user.notebooks if user_signed_in?
    @note = Note.find(params[:id])
    @comments = @note.comments.paginate(:page => params[:page], :per_page => 5) 
    if(user_signed_in?)
      @note_owner = @note.user_id
    else
      @note_owner = -1
    end
  end

  def upload_note
    @note = current_user.notes.build(upload_note_params)
    if @note.save
        flash[:success] = "Saved successfully!" 
        redirect_to notes_path
    else
      flash[:error] = "Save unsuccessful. Please make sure all three fields have a value!"
      redirect_to static_pages_home_path
    end

  end

  def create_comment
    @note = Note.find(params[:id])
    @comment = current_user.comments.build(create_comment_params)
    if @comment.save
      @comment.update_attribute(:note_id, '#{@note.id}')
      flash[:success] = "Comment posted successfully!" 
      redirect_to @note
    else
      flash[:alert] = "Sorry, something went wrong. Please try again." 
      redirect_to @note
    end
  end

  private
    def create_comment_params
      params.require(:note).permit(:content)
    end
    def upload_note_params
      params.require(:note).permit(:title, :content, :notebook_id, :avatar, :professor, :university, :class_subject)
    end

    def note_params
      params.require(:note).permit(:title, :content, :university, :notebook_id, :class_subject, :professor, :tags)
    end

    def correct_user
      @note = current_user.notes.find_by(id: params[:id])
      redirect_to root_url if @note.nil?
    end
end

app/helpers/notes_helper.rb
module NotesHelper

	def cache_key_for_all_notes
    	"all_notes/#{current_user.notes.maximum(:updated_at)}"
  	end	
	def cache_key_for_note(note)
    	"note/#{note.id}/#{note.updated_at}"
  	end

  	def cache_key_for_all_comments(comments)
  		"all_comments/#{comments.maximum(:updated_at)}"
  	end
  	def cache_key_for_comment(comment)
  		"comment/#{comment.id}/#{comment.updated_at}"	
  	end

    def cache_key_for_search(keyword, notes)
      "search/#{keyword}/#{notes.maximum(:updated_at)}"
    end
end

app/views/notes/create.js.erb
$("#note_save_msg").html("Note Saved!");
$("#note_save_msg").show();

app/views/notes/edit.html.erb
<% provide(:title, "Edit Note") %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <meta name="fragment" content="!">
        <meta name="author" content="Austin Anderson">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="contact" content="austin@rarebreedstudios.com">
        <meta name="copyright" content="Austin Anderson. All rights reserved">
        <meta charset="utf-8">
        <title>textAngular :: Lightweight Angular.js, Javascript Wysiwyg/Text-Editor</title>
        <link rel="shortcut icon" href="images/favicon.png">
        <script src='http://code.jquery.com/jquery-1.9.1.min.js'></script>

        <%= javascript_include_tag "textAngular-rangy.min", "textAngular-sanitize.min", "textAngular.min", "bootstrap-tags" %>
        <%= stylesheet_link_tag "bootstrap-tags" %>
        <!-- <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,300"> -->
    <link rel="stylesheet" href="http://textangular.com/css/style.css" type="text/css">
    </head>

    <body>
            <div id="note_save_msg" style="display: none;"></div>
            <div id="ng-app" ng-app="textAngularDemo" ng-controller="demoController" class="ng-scope">
                <br>
                <br>
                <!--note title-->
                <table style="border-spacing:20px 20px;" cellspacing="30px">
                    <div class="form-group">
                       <tr>
                            <td> 
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Title:</label>
                            </td>
                            <td> 
                                <input class="form-control" type="text" ng-model="title"
                                        style="width: 500px">
                            </td>
                        </tr>
                    </div>
                    
                    <!--note university-->
                    <div class="form-group">
                        <tr>
                            <td><br/>   
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">University:</label>
                            </td>
                            <td><br/>  
                                <input class="form-control" type="text" ng-model="university" style="width: 250px">
                            </td>
                        </tr>
                    </div>

                    <!--note class-->
                    <div class="form-group">
                       <tr>
                            <td> <br/> 
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Class:</label>
                            </td>
                            <td><br/> 
                                <input class="form-control" type="text" ng-model="notes_class" style="width: 250px">
                            </td>
                        </tr>
                    </div>

                    <!--note prof-->
                    <div class="form-group">
                       <tr>
                            <td><br/>  
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Professor:</label>
                            </td>
                            <td><br/> 
                                <input class="form-control" type="text" ng-model="professor" style="width: 250px">
                            </td>
                        </tr>
                    </div>
                    
                    <!--notebook-->
                    <div class="form-group">
                       <tr>
                            <td> <br/> 
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Notebook: </label>
                            </td>
                            <td><br/> 
                                <select class="form-control" id="notebook_id" style="width:200px" ng-model="notebook">
                                    <%@notebooks.each do |option|%>
                                    <option value="<%=option.id%>"><%=option.title%></option>
                                    <%end%>
                                </select>  
                            </td>
                        </tr>
                    </div>


                    <div id="div-item-data" data-item-title="<%= @note.title %>" data-item-university="<%=@note.university %>"
                    data-item-class="<%= @note.class_subject %>" data-item-prof="<%= @note.professor %>" 
                    data-item-content="<%= @note.content.html_safe %>" 
                    data-item-id="<%= @note.id %>"></div>

                    
                </table>
                <br/>
                <br>

                <!--Angular Text Editor-->
                    <div text-angular ng-model="htmlContent" name="demo-editor" ta-text-editor-class="border-around" ta-html-editor-class="border-around"></div>
                <br>

                <!--<p ng-bind="htmlContent" class="text-left text-med text-gray"></p>-->


                <!--Save Button-->
                <button class="btn btn-success" ng-click="save()"
                        style=" background-color: white; border-color: black; width: 120px; color:black; font-weight: bold;
                        margin-top: 20px; float: right; margin-right: 50px">
                    <!-- <span class="glyphicon glyphicon-save"></span>&nbsp&nbsp Save &nbsp&nbsp -->
                    <span>Save</span>
                </button>
                <br>
                <br>
            </div>
        <!-- End Container -->

    </body>

    <script type="text/javascript">
            angular.module("textAngularDemo", ['textAngular'])
                    .controller("demoController", function demoController($scope, $http, $window) {
                        var div = document.getElementById('div-item-data');
                        $scope.title = div.getAttribute("data-item-title");
                        $scope.university = div.getAttribute("data-item-university");
                        $scope.notes_class = div.getAttribute("data-item-class");
                        $scope.professor = div.getAttribute("data-item-prof");
                        $scope.htmlContent = div.getAttribute("data-item-content");
                        $scope.noteid = div.getAttribute("data-item-id");

                        $scope.save = function(){
                            var noteObj = {
                                id: $scope.noteid,
                                title: $scope.title,
                                content: $scope.htmlContent,
                                university: $scope.university,
                                class_subject: $scope.notes_class,
                                professor: $scope.professor
                            }
                            //confirm(noteObj.content);
                            $http.post('/edit_notes', noteObj).success(function(data, status){
                                    // confirm(status);
                                    $window.location.href = '/notes';
                                }).error(function(data, status){
                                    // confirm(status);    
                                });
                        }
                    });
        </script>
        <script src='http://code.jquery.com/jquery-1.9.1.min.js'></script>
</html>

app/views/notes/index.html.erb
<% provide(:title, "All Notes") %>
<!--<div class="panel panel-default">
  <div class="panel-body"></div>
</div>
-->
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    
  <h3 style="margin-top: 30px; color:black">Notes by <span style="color:green"><%=user_name current_user %></span></h3>
  <span style="margin-top: 30px; color:black"><i><%= pluralize(@notes.count, 'note')%></i></span>

  <%= will_paginate %>
  <%cache(cache_key_for_all_notes) do%>
  <table class="table table-striped" style="width: 95%; margin-left:2%;">
  	 <thead>
        <tr>
          <th>Title</th>
          <th>Notebook</th>
          <th>University</th>
          <th>Class</th>
          <th>Professor</th>
        </tr>
      </thead>

      <tbody class="notes">
            
          <% @notes.each do |note| %>
          <% cache(cache_key_for_note(note)) do%>
          <tr style="color:grey">
              <td><%= link_to note.title, note, :style => "color:#00B87A"  %></td>
              <td><%= link_to note.notebook.title, note.notebook if !note.notebook.nil? %></td>
              <td><%=  note.university %></td>
              <td><%=  note.class_subject %></td>
              <td><%=  note.professor %></td> 
          </tr>
          <%end%>
          <%end%>
      </tbody>
  </table>
  <%end%>
  <%= will_paginate %>

app/views/notes/new.html.erb
<% provide(:title, "New Note") %>
    <link rel="shortcut icon" href="images/favicon.png">
     <%= javascript_include_tag "textAngular-rangy.min", "textAngular-sanitize.min", "textAngular.min", "bootstrap-tags" %>
     <%= stylesheet_link_tag "bootstrap-tags" %>
    <link rel="stylesheet" href="http://textangular.com/css/style.css" type="text/css">

    <body>
      <% cache(cache_key_for_user(current_user)) do %>
            <div id="note_save_msg" style="display: none;"></div>
            <div id="ng-app" ng-app="textAngularDemo" ng-controller="demoController" class="ng-scope">
                <br>
                
                
                <h4 style="margin-left:40%; font-weight:bold">New Note</h4>
                <br>
                <!--note title-->
                <table style="border-spacing:20px 20px;" cellspacing="30px">
                    <div class="form-group">
                       <tr>
                            <td> 
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Title:</label>
                            </td>
                            <td> 
                                <input class="form-control" type="text" ng-model="title" style="width: 500px">
                            </td>
                        </tr>
                    </div>
                    
                    <!--note university-->
                    <div class="form-group">
                        <tr>
                            <td><br/>   
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">University:</label>
                            </td>
                            <td><br/>  
                                <input class="form-control" type="text" ng-model="university" style="width: 250px">
                            </td>
                        </tr>
                    </div>

                    <!--note class-->
                    <div class="form-group">
                       <tr>
                            <td> <br/> 
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Class:</label>
                            </td>
                            <td><br/> 
                                <input class="form-control" type="text" ng-model="notes_class" style="width: 250px">
                            </td>
                        </tr>
                    </div>

                    <!--note prof-->
                    <div class="form-group">
                       <tr>
                            <td><br/>  
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Professor:</label>
                            </td>
                            <td><br/> 
                                <input class="form-control" type="text" ng-model="professor" style="width: 250px">
                            </td>
                        </tr>
                    </div>
                    
                    <!--notebook-->
                    <div class="form-group">
                       <tr>
                            <td> <br/> 
                                <label class="col-sm-1 control-label" style="margin-left: 50px; font-weight: bold; font-size:17px">Notebook: </label>
                            </td>
                            <td><br/> 
                                <select class="form-control" id="notebook_id" style="width:200px" ng-model="notebook">
                                    <%@notebooks.each do |option|%>
                                    <option value="<%=option.id%>"><%=option.title%></option>
                                    <%end%>
                                </select>  
                            </td>
                        </tr>
                    </div>
                </table>
                <br/>
                <br>

                <!--Angular Text Editor-->
                    <div text-angular ng-model="htmlContent" name="demo-editor" ta-text-editor-class="border-around" ta-html-editor-class="border-around"></div>
                <br>

                <!--<p ng-bind="htmlContent" class="text-left text-med text-gray"></p>-->


                <!--Save Button-->
                <button class="btn btn-success" ng-click="save()"
                        style=" background-color: white; border-color: black; width: 120px; color:black; font-weight: bold;
                        margin-top: 20px; float: right; margin-right: 50px">
                    <!-- <span class="glyphicon glyphicon-save"></span>&nbsp&nbsp Save &nbsp&nbsp -->
                    <span>Save</span>
                </button>
                <br>
                <br>
            </div>
        <!-- End Container -->
      <% end %>
    </body>
    <script src='http://code.jquery.com/jquery-1.9.1.min.js'></script>
    <script type="text/javascript">

            angular.module("textAngularDemo", ['textAngular'])
                    .controller("demoController", function demoController($scope, $http, $window) {

                        $scope.save = function(){

                            var noteObj = {
                                title: $scope.title,
                                content: $scope.htmlContent,
                                university: $scope.university,
                                class_subject: $scope.notes_class,
                                professor: $scope.professor,
                                notebook_id: $scope.notebook
                                
                            }
                            //confirm(noteObj.notebook);
                            $http.post('/notes', noteObj).success(function(data, status){
                                    $window.location.href = '/notes';
                                }).error(function(data, status){
                                     confirm(status);    
                                });
                        }

                    });
        </script>
        <script src='http://code.jquery.com/jquery-1.9.1.min.js'></script>
</html>

app/views/notes/search.html.erb
	<% provide(:title, "Search Results") %>
	<%if @notes.count == 0%>
	<br/>
	  	  Sorry, there's nothing for <span style="color:brown"><%=@keyword %></span>
	<%else%>
	<%if Rails.application.config.old.length < 1%>
		<h3>Search results</h3>
	<%else%>
		<h3>Matched <%=pluralize(@notes.count, "note")%> for <span style="color:blue"><%=Rails.application.config.old %></span></h3>
	<%end%>
	<%end%>
	<%= will_paginate @notes%>
	<br/>
	<%cache(cache_key_for_search(Rails.application.config.old, @notes)) do%>
	<table >
	  <% @notes.each do |item| %>
	  	<%cache(cache_key_for_search_note(Rails.application.config.old, item)) do%>		

	    <tr style="border-bottom:1px solid black;">
	<span style="float:center">_________________________________________________________________</span>

	<h4 ><strong><%= link_to(item.title, item, {:style=>'color:green;'}) %></strong></h4>
	<div style="float:right">
	<span style="color:green"><%=item.get_upvotes.size%>  </span>  <br/>
	<i class="fa fa-arrow-up"></i><br/>
	<i class="fa fa-arrow-down"></i><br/>
	<span style="color:red"><%=item.get_downvotes.size%>  </span>
	</div>
	<h5><span class="text-primary"><% if !item.university.nil?%><span style="color:red">University: <%=item.university %></span><%end%><%if !item.class_subject.nil?%><span style="color:violet"> Class: <%=item.class_subject %> </span><%end%><%if !item.professor.nil?%><span style="color:brown"> Professor: <%=item.professor %></span><%end%></span></h5>
	<%= item.content.html_safe.truncate_words(7) %>
	<br/>
	<span style="color:blue"><%=pluralize(item.comments.count, 'comment')%></span>
	
	<br/>

	<%if item.avatar.exists?%>
	<%= link_to(image_tag(item.avatar.url(:thumb)), item.avatar.url) if item.avatar.content_type != "application/pdf"%>
	<%= link_to(item.avatar_file_name, item.avatar.url) if item.avatar.content_type == "application/pdf"%><br/>
	<%end%>
	<small style="color:grey">Last modified <%= time_ago_in_words item.updated_at.to_s %> ago by <%= user_name item.user %>.</small>
	
	<br/>
	
</tr>

<% end %>

	  <%end%>
	</table>
<% end %>
	<%= will_paginate @notes%>

app/views/notes/show.html.erb
<% provide(:title, "Note") %>

<!-- 
<html lang="en" ng-app="noteIt">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src='http://code.jquery.com/jquery-1.9.1.min.js'></script>  -->
        
        <%= stylesheet_link_tag "bootstrap-tags" %>
        <%= stylesheet_link_tag "vote" %>
        
    <!-- </head> -->

            <br>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><span style="color:green"><%= @note.title%> </span>
                    <%user = User.find(@note.user_id)%>
                    <br/><h4 style="color:brown"> By <%= link_to (user_name user), user%></h4>
                        <%if user_signed_in?%>
                        <div class="btn-group" style="float:right">
                          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" 
                                    aria-expanded="false" style="height:30px; width: 35px; border-color:darkred">
                            <span class="caret"></span>
                          </button>
                          
                          <ul class="dropdown-menu pull-right">
                            <li><%= link_to 'Edit',edit_note_path %></li>
                            <li><a href="#">Set as Private Note</a></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "Delete", @note, :method => :delete, :data => {:confirm => "You sure you want to delete this note?" } %></li>
                          </ul>
                          <%end%>
                        </div>
                    </h3>
                    <span class="text-primary"><span style="color:red">University: <%=@note.university %></span><br/><span style="color:violet">Class: <%=@note.class_subject %> </span><br/><span style="color:brown">Professor: <%=@note.professor %></span></span>
                    
                </div>

                <div class="panel-body"><%=@note.content.html_safe%> 
                </div>
            </div>

            
            <%if @note.avatar_file_name %>
            <% if @note.avatar_content_type =~ /image*/ %>
                <div>
                        <%= link_to "View original image", @note.avatar.url%> 
                        <br/>   
                        <%= image_tag @note.avatar.url(:medium) %>
                        
                </div>
            <%else%>
                <div>
                    <%= link_to "View uploaded file", @note.avatar.url%>
                </div>
            <%end%>
            <%end%>
            <section class="panel panel-default" style="position:fixed; bottom: 5%; left:1%">
            
                <% if(user_signed_in? && current_user.id != @note_owner) %>
                    <%= render 'partials/vote' %>
                <%else%>
                    <%= render 'partials/view_vote' %>
                <%end%>
            </section>

            <br>
            <hr>
            <section>
            <!-- Comments Form -->
                <% if user_signed_in? %>
                <% flash.each do |message_type, message| %>
                    <div class="alert alert-<%= message_type %>"><%= message %></div>
                <% end %>
                <div >
                    <h4>Leave a Comment:</h4>
                    <%= render 'partials/leave_a_comment' %>
                </div>
                <!-- End comments form -->
                <%else%>
                    <div><i>You must be signed in to post comments.</i></div>
                <%end%>
                <!-- Comments -->

            </section>
            <br/>
            <% if @note.comments.all.count > 0 %>
            <section>
                <h3>Recent comments</h3>
                <br/>
                <%if @note.comments.all.count > 5%>
                <small>
                  <%= form_for(:comment, :url => comments_show_path) do |f| %>
                    <%= hidden_field_tag :note_id, @note.id %>
                    <%= f.submit "View all (#{pluralize(@note.comments.all.count, 'comment')})"%>
                  <% end %>
                </small>
                <br/>
                <%end%>
                 <%= render 'partials/show_comments'%>  
            <!-- End Comments -->
            </section>
            <%else%>
                <% if user_signed_in? %><section><h3>Be the first to comment!</h3></section> <%end%>
            <%end%>

             
                
    <!-- </body> -->

<!-- </html> -->
<script>
            document.write('<base href="' + document.location + '" />');
        </script>
        <script data-require="angular.js@1.2.x" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.17/angular.min.js" data-semver="1.2.16"></script>

<%= javascript_include_tag "bootstrap-tags" %>
        <%= javascript_include_tag "vote" %>

app/views/notes/update.js.erb
<%if @vote_type == :upvote%>
	$("#upvote_form_form").css("color", "green");
	$("#downvote_form_form").css("color", "black");
	$("#upvote_count").html('<%=@note.get_upvotes.size%>');
	<%if(@note.get_downvotes.size != 0)%>
		$("#downvote_count").html('<%=-@note.get_downvotes.size%>');	
	<%else%>
		$("#downvote_count").html('0');	
	<%end%>
	
<%else%>
	$("#upvote_form_form").css("color", "black");
	$("#downvote_form_form").css("color", "red");
	$("#upvote_count").html('<%=@note.get_upvotes.size%>');
	<%if(@note.get_downvotes.size != 0)%>
		$("#downvote_count").html('<%=-@note.get_downvotes.size%>');	
	<%else%>
		$("#downvote_count").html('0');	
	<%end%>
<%end%>