config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#welcome_page'
  get 'static_pages/home'

  get 'comments/new'
  post 'comments/show'
  post 'notes/show_user_notes'
  resources :notes
  resources :notebooks
  resources :comments
  resources :relationships,       only: [:create, :destroy]
  
  post 'search' => 'notes#search'
  get 'search' => 'notes#search'
  post 'upload-note' => 'notes#upload_note'
  post 'edit_notes' => 'notes#edit_notes'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions" }
  resources  :users, :only => [:index, :show] do
    member do
      get :following, :followers
    end
  end

  get 'feed' => 'users#feed'

  
end

app/views/partials/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/partials/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'partials/unfollow' %>
  <% else %>
    <%= render 'partials/follow' %>
  <% end %>
  </div>
<% end %>

app/views/partials/_leave_a_comment.html.erb
<div>
	<%= form_for Comment.new do |form| %>
  		<%=hidden_field_tag :note_id, @note.id %>
      
  		<%= form.text_field :body%>
  		<%= form.submit "Post comment" %>
	<% end %>
</div>

app/views/partials/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->

    
    <div class="navbar-header">
        <!-- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button> -->
        <a class="navbar-brand" rel="home" href="/" title="NoteIt - Homepage">NoteIt</a>
    </div>
    
    <div class="collapse navbar-collapse">
        <%if !(request.env['PATH_INFO'] == root_path) %>
        <div class="col-sm-3 col-md-3" style="margin-top: 10px"> 
            <%= form_tag search_path, :html => { :class => 'navbar-form' } do |f| %>
                <%= text_field_tag :search, nil, placeholder: 'Search notes..' %>
                <%= submit_tag "Search", class: "btn" %>
               <!-- <%= button_tag do %>
                    <i class="icon-search"></i>
                <% end %>-->
            <%end%>
        </div>
        <%end%>


        <ul class="nav navbar-nav pull-right">

            

            <% if user_signed_in? %>

                <% if !(request.env['PATH_INFO'] == static_pages_home_path) %>
                <li>
                    <%= link_to "Find users", users_path %>
                </li>

                <li>
                    <%= link_to "Your notes", notes_path  %>
                </li>
                <li>
                    <%= link_to "View feed", feed_path %>
                </li>
                
                <%end%>
                <li>
                    <%= link_to "Create Note", '/notes/new' %>
                </li>

                <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                        <ul class="dropdown-menu">

                            <li>
                                <%= link_to "Edit Profile", edit_user_registration_path %>
                            </li>

                            <li role="separator" class="divider"></li>
                            <li>
                                <% if user_signed_in? %>
                                    <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
                                <%else%>
                                    <%= link_to "Log in", new_user_session_path %>
                                <%end%>
                            </li>
                        </ul>
                </li>

            <% else %> <!-- User not logged in -->

                <li>
                    <%= link_to "Log in", new_user_session_path %>
                </li>


                <li>
                    <%= link_to "Sign up", new_user_registration_path%>
                </li>

            <% end -%>
            <!-- End is user logged in? -->


            
        </ul>
        
    </div>

</nav>

<script>
     $(document).ready(function(){
        $('.dropdown-toggle').dropdown()
    });
</script>

app/views/partials/_new_comment.html.erb
<div>
  <!-- Comments Form -->
    <div class="well col-lg-8 col-centered">
        <h4>Leave a Comment:</h4>
        <%= form_for [@note, Comment.new] do |form| %>
          <%= form.hidden_field :user_id, value: @note.user_id %>
          <%= form.text_area :body%>
          <%= form.submit "Add Comment" %>
        <% end %>
    </div>
  <!-- End comments form -->
</div>

app/views/partials/_new_notebook.html.erb
<div>
	<%= form_for :notebook, url: notebooks_path do |form| %>
  		<%= form.label :title %>
  		<%= form.text_field :title%>
  		<%= form.submit "Create" %>
	<% end %>
</div>

app/views/partials/_notebooks.html.erb
<div>
	<ul class="notebooks">
  	<% @notebooks.each do |notebook| %>
    <li>
      <%= link_to notebook.title, notebook %>
    </li>
  <% end %>
</ul>
<div>

app/views/partials/_show_comments.html.erb
<div>
  <%cache(cache_key_for_all_comments @comments) do%>	
	<table class="comments">
  	
      <% @comments.each do |comment| %>
    	<%cache(cache_key_for_comment(comment)) do%>
     
      <tr>
   	   		<div class="media col-lg-8 col-centered">
    	
      			<a class="pull-left" href="#">
        	 		<img class="media-object" src="http://placehold.it/64x64" alt="">
      			</a>
      			<div class="media-body">
      				<span style="color:grey">Posted by <%=user_name User.find(comment.user_id)%> <%= time_ago_in_words comment.created_at%> ago.</span>
              <br/>
      				<h4 >
      					<%= comment.body %>
      				</h4>
      			</div>
      		</div>
    	</tr>
      <%end%>

  		<% end %>
  </table>
  <%end %>
</div>

app/views/partials/_sidebar.html.erb
<% @user ||= current_user %>

<div class="col-md-3">
    <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
            <%= image_tag(current_user.avatar.url(:thumb) , class: "img-responsive") %>
            
        </div>
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
            <div class="profile-usertitle-name">
                <%= @user.name %>
            </div>
            <div class="profile-usertitle-job">
                <%= @user.email %>
            </div>
           <%= render 'partials/stats' %>
            
        </div>
    </div>
</div>

app/views/partials/_stats.html.erb
<% @user ||= current_user %>

<%= render 'partials/follow_form' if !current_user.nil? %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/partials/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/partials/_upload_note.html.erb
<div>
	<%= form_for :note, url: upload_note_path, html: { multipart: true } do |form| %>
  		<table>
      <tr><td><%= form.label :title %></td>
  		<td><%= form.text_field :title%></td></tr>
  		<tr><td><%= form.label :keywords%></td>
  		<td><%= form.text_field :content %></td></tr>
      <tr><td><%= form.label :university%></td>
      <td><%= form.text_field :university %></td></tr>
      <tr><td><%= form.label :professor%></td>
      <td><%= form.text_field :professor %></td></tr>
      <tr><td><%= form.label :class%></td>
      <td><%= form.text_field :class_subject %></td></tr>
  		<% options = options_from_collection_for_select(@notebooks, 'id', 'title') %>
		<tr><td><%= form.label :Notebook%></td>
		<td><%= form.select :notebook_id,  options %></td></tr>
  		<tr><td><%= form.file_field :avatar %></td>
  		<td><%= form.submit "Upload" %></td></tr>
    </table>
	<% end %>
</div>

app/views/partials/_view_vote.html.erb
<div id = "upvote_form">
	<div id="upvote_count"><%=@note.get_upvotes.size%></div>
	<div id = "upvote_form_form">
  			Upvotes
	</div>
</div>

<div id = "downvote_form">
	<div id = "downvote_form_form">
			Downvotes
	</div>
	<div id = "downvote_count">
		<%if(@note.get_downvotes.size != 0)%>
			<%=-@note.get_downvotes.size%>
		<%else%>
			0
		<%end%>
	</div>
</div>

app/views/partials/_vote.html.erb
<div id = "upvote_form">
	<div id="upvote_count"><%=@note.get_upvotes.size%></div>
	<div id = "upvote_form_form">
		<%= form_for(@note, remote: true) do |f| %>
  		<div><%= hidden_field_tag :upvote, current_user %></div>
  		<%= button_tag( :class => "button_green") do %>
  			<i class="fa fa-arrow-up"></i>
		<% end %>
		<% end %>
	</div>
</div>

<div id = "downvote_form">
	<div id = "downvote_form_form">
		<%= form_for(@note, remote: true) do |f| %>
  		<div><%= hidden_field_tag :downvote, current_user %></div>
  		<%= button_tag( :class => "button_green") do %>
  			<i class="fa fa-arrow-down"></i>
		<% end %>
		<% end %>
	</div>
	<div id = "downvote_count">
		<%if(@note.get_downvotes.size != 0)%>
			<%=-@note.get_downvotes.size%>
		<%else%>
			0
		<%end%>
	</div>
</div>