config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#welcome_page'
  get 'static_pages/home'

  get 'comments/new'
  post 'comments/show'
  post 'notes/show_user_notes'
  resources :notes
  resources :notebooks
  resources :comments
  resources :relationships,       only: [:create, :destroy]
  
  post 'search' => 'notes#search'
  get 'search' => 'notes#search'
  post 'upload-note' => 'notes#upload_note'
  post 'edit_notes' => 'notes#edit_notes'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions" }
  resources  :users, :only => [:index, :show] do
    member do
      get :following, :followers
    end
  end

  get 'feed' => 'users#feed'

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  default_scope -> { order(created_at: :desc) }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  #validates :name, length: {maximum: 50}
  
  has_many :notes
  has_many :notebooks
  has_many :comments

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed

  has_many :followers, through: :passive_relationships, source: :follower

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Note.includes(:comments).where("notes.user_id IN (#{following_ids})
                     OR notes.user_id = :user_id", user_id: id)
  end

  def largeimage
    "http://graph.facebook.com/#{self.uid}/picture?type=large/"
  end

  def normalimage
    "http://graph.facebook.com/#{self.uid}/picture?type=normal/"
  end

  def self.find_for_facebook_oauth(omniauth)
    puts "yay!!2"
    if user = User.find_by_email(omniauth.info.email)
      if omniauth.info.image.present?
        user.update_attribute(:image, omniauth.info.image)
      end
      user
    else # Create a user with a stub password. 
      User.create!(:email => omniauth.info.email,
                   :name => omniauth.info.name,
                   :avatar => "https://graph.facebook.com/#{auth["uid"]}/picture?type=large",
                   :password => Devise.friendly_token[0,20])
    end
  end

  def self.from_omniauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      # user.avatar =  "https://graph.facebook.com/#{auth["uid"]}/picture?type=large/"
      user.save
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else

        user = User.create(
          name:auth.extra.raw_info.name,
          # uid:auth.uid,
          email:auth.info.email,
          avatar: "https://graph.facebook.com/#{auth["uid"]}/picture?type=large/",
          password:Devise.friendly_token[0,20]
          )
      end    
    end
  end



  def self.new_with_session(params, session)
    puts "yay!!5"
   
    super.tap do |user|
      if omniauth = session["devise.facebook_data"]
        user.email = omniauth.info.email
        user.name = omniauth.info.name
        # user.avatar = omniauth.info.image
      end
    end
  end

  has_attached_file :avatar, :styles => { :medium => "400x400>", :thumb => "400x400" }, :default_url => ActionController::Base.helpers.asset_path('missing.png')
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end


  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   # super
  #   @notebooks = current_user.notebooks
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
     super
  end

  # POST /resource/sign_in
  def create
     super
  end

  # DELETE /resource/sign_out
  def destroy
     super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

def index
	@users = User.paginate(page: params[:page])
end

def show
	@user = User.find(params[:id])
end

def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'users/show_follow'
end

def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'users/show_follow'
end

def feed
    @feed_items = current_user.feed.paginate(page: params[:page]) if stale?(current_user.feed.paginate(page: params[:page]))
end

end

app/helpers/users_helper.rb
module UsersHelper

def cache_key_for_feed(feed_items)
   "feed/#{feed_items.count}/#{feed_items.maximum(:updated_at)}"
end	

def cache_key_for_feed_item(item)
	"note/#{item.id}/#{item.updated_at}"
end

def cache_key_for_users(users)
	"users/#{users.count}/#{users.maximum(:updated_at)}"
end

def cache_key_for_user(user)
  	"user/#{user.id}/#{user.updated_at}"
end

def count_upvotes(user)
	notes =Note.where(user_id = user)
	count = 0
	user.notes.each do |note|
		count += note.votes_for.up.by_type(User).voters.count
	end
	return count
end

def count_downvotes(user)
	notes =Note.where(user_id = user)
	count = 0
	user.notes.each do |note|
		count += note.votes_for.down.by_type(User).voters.count
	end
	return count
end

end

app/views/users/feed.html.erb
<% provide(:title, "Your feed") %>
<h2 style="color:brown">Activity feed</h2>

<%= will_paginate @feed_items%>
<br/>
<%cache(cache_key_for_feed(@feed_items)) do%>
<table >
<% @feed_items.each do |item| %>
<% cache(cache_key_for_feed_item(item)) do%>
<tr >
	<span style="float:center">_________________________________________________________________</span>

	<h4 ><strong><%= link_to(item.title, item, {:style=>'color:green;'}) %></strong></h4>
	<div style="float:right">
	<span style="color:green"><%=item.get_upvotes.size%>  </span>  <br/>
	<i class="fa fa-arrow-up"></i><br/>
	<i class="fa fa-arrow-down"></i><br/>
	<span style="color:red"><%=item.get_downvotes.size%>  </span>
	</div>
	<h5><span class="text-primary"><% if !item.university.nil?%><span style="color:red">University: <%=item.university %></span><%end%><%if !item.class_subject.nil?%><span style="color:violet"> Class: <%=item.class_subject %> </span><%end%><%if !item.professor.nil?%><span style="color:brown"> Professor: <%=item.professor %></span><%end%></span></h5>
	<%= item.content.html_safe.truncate_words(7) %>
	<br/>
	<span style="color:blue"><%=pluralize(item.comments.count, 'comment')%></span>
	
	<br/>

	<%if item.avatar.exists?%>
	<%= link_to(image_tag(item.avatar.url(:thumb)), item.avatar.url) if item.avatar.content_type != "application/pdf"%>
	<%= link_to(item.avatar_file_name, item.avatar.url) if item.avatar.content_type == "application/pdf"%><br/>
	<%end%>
	<small style="color:grey">Last modified <%= time_ago_in_words item.updated_at.to_s %> ago by <%= link_to((user_name item.user),item.user) %>.</small>
	
	<br/>
	
</tr>
<br/>
<%end%>
<%end%>
</table>
<%end%>

<%= will_paginate @feed_items%>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h3 style="color:brown"> NoteIt users </h3>
 <%= will_paginate %><br/>
 <%cache(cache_key_for_users(@users)) do%>
 <table>
 	<% @users.each do |user| %>
 	
 	<tr>
 	<span style="float:center">_________________________________________________________________</span><br/>
 		<span style="float:left">&nbsp <%= image_tag 'missing.png', size: '55'%></span>
 		<span style="color:green">&nbsp <%=link_to user_name(user), user %></span> <br/>
 		<span style="color:blue">&nbsp <%= pluralize(user.notes.count,'note')%></span> <br/>
 		<span style="color:grey">&nbsp <%= pluralize(user.notebooks.count,'notebook') %></span><br/>
 	</tr>
 	<%end%>
 </table>
<%end%>

 <%= will_paginate %>
 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h2 style="color:black"><%= user_name @user%></h2>
<div style="color:black">
	<h3><span style="color:blue"><%=(pluralize(@user.notes.count, 'note')) %></span><br/>
	<% if @user.notes.count != 0 %>
	<small>
	<%= form_for(:note, :url => notes_show_user_notes_path) do |f| %>
  	<%= hidden_field_tag :user_id, @user.id %>
  	<%= f.submit "View notes"%>
	<% end %>
	</small>
	<br/>
	<%end%>
	<span style="color:grey"><%= pluralize(@user.notebooks.count, 'notebook') %></span><br/>
	<br/><br/>
	<h4>Aggregate note statistics of <span style="color:grey"><%= user_name @user %></span></<br/><br/>
	<span style="color:green"><%=pluralize(count_upvotes(@user),'upvote')%></span><br/>
	<span style="color:red"><%=pluralize(count_downvotes(@user), 'downvote')%></span><br/></h4></h3>
<div>
<br/>
<br/>
<br/>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-md-8">
    <%if @user.name.nil?%>
    <h3 style="color:green"> <%= link_to @user.email, @user %> </h3>
    <%else%>
    <h3 style="color:green"> <%= link_to @user.name, @user %> </h3>
    <%end%>
    <h4 style="color:grey"><%= @title %></h4>
    <% if @users.any? %>
      
      <%cache(cache_key_for_users(@users)) do%>
       <%= will_paginate %>
      
       <table>
        <% @users.each do |user| %>
        <%cache(cache_key_for_user(user)) do%>
        
        <tr>
        <span style="float:center">_________________________________________________________________</span><br/>
    <span style="float:left">&nbsp <%= image_tag 'missing.png', size: '55'%></span>
    <span style="color:green">&nbsp <%=link_to user_name(user), user %></span> <br/>
    <span style="color:blue">&nbsp <%= pluralize(user.notes.count,'note')%></span> <br/>
    <span style="color:grey">&nbsp <%= pluralize(user.notebooks.count,'notebook')%></span><br/>
        </tr>
        
        <%end%>
        <%end%>
      </table>
       <%= will_paginate %>
      <%end%>

    <%else%>
        Nobody here
    <% end %>
  </div>
</div>